name: Build kernel

on: 
  release:
    types: [published]
  push:
    branches: 
      - V10

jobs:
  build: 
    runs-on: ubuntu-16.04
    
    env:
      ARCH: arm64
      KBUILD_BUILD_HOST: 4pda
      KBUILD_BUILD_USER: dmipin02
    
    steps:
      - uses: actions/checkout@v2

      - name: Freeze Actions timeout
        run: touch /tmp/keepalive

      - name: Install packages
        run: |
          sudo apt-get update -qyy
          sudo apt-get install wget curl bc make git build-essential libssl-dev libglib2.0-dev curl flex g++-multilib gcc-multilib gnupg gperf lib32ncurses5-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libwxgtk-media3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev
      
      - name: Download toolchain
        run: |
          git clone https://github.com/Jprimero15/lolz_clang --depth=1 clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r4 --depth=1 gcc64
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r41 --depth=1 gcc32
          export PATH=$PATH:$PWD/clang/bin:$PWD/gcc64/bin:$PWD/gcc32/bin

      - name: Prepare build
        run: make O=out ARCH=arm64 kali_olive_defconfig

      - name: Build kernel
        run: make -j32 O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-androidkernel- CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - uses: actions/upload-artifact@v2
        with:
          path: out/Image.gz

      - uses: actions/upload-artifact@v2
        with:
          path: out/Image.gz-dtb


